blank_issues_enabled: false
contact_links:
  - name: 🙋 Ask a question
    url: https://github.com/chrisbarnes2000/HytaleBlockChain/pi-platform-docs/discussions
    about: Ask questions and discuss with other community members